"""empty message

Revision ID: 00903b388a68
Revises: e7428c5e0a3e
Create Date: 2025-12-06 22:55:39.065875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00903b388a68'
down_revision = 'e7428c5e0a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
