"""empty message

Revision ID: 0117e97d12cd
Revises: f83161008aec
Create Date: 2025-12-18 22:42:10.094569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0117e97d12cd'
down_revision = 'f83161008aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
