"""add shipment table

Revision ID: 27ed2fbcf71c
Revises: 6c3aca47788a
Create Date: 2025-12-20 11:53:54.696738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ed2fbcf71c'
down_revision = '6c3aca47788a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
