"""add url column to variation table

Revision ID: 2a4c02c37e0c
Revises: 9fbb1fb25375
Create Date: 2025-12-12 22:27:41.396187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4c02c37e0c'
down_revision = '9fbb1fb25375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_variations', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
