"""empty message

Revision ID: 31572b9c8148
Revises: b49afcbf3fce
Create Date: 2025-12-11 09:39:15.082135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31572b9c8148'
down_revision = 'b49afcbf3fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
