"""Add payment table

Revision ID: 33314337f189
Revises: 0117e97d12cd
Create Date: 2025-12-19 23:19:22.255923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33314337f189'
down_revision = '0117e97d12cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_ss', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_ss')
        batch_op.drop_column('payment_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_ss', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('payments')
    # ### end Alembic commands ###
