"""empty message

Revision ID: 35bffb29002c
Revises: 7dcb645d5492
Create Date: 2025-12-20 11:55:51.244361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bffb29002c'
down_revision = '7dcb645d5492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
