"""edit orders table renamed to variation_id

Revision ID: 3919a0506632
Revises: 771bae4e0637
Create Date: 2025-12-15 15:52:43.282232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3919a0506632'
down_revision = '771bae4e0637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('orders_inventory_variation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_variations', ['variation_id'], ['id'])
        batch_op.drop_column('inventory_variation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_variation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_inventory_variation_id_fkey'), 'inventory_variations', ['inventory_variation_id'], ['id'])
        batch_op.drop_column('variation_id')

    # ### end Alembic commands ###
