"""Add variations

Revision ID: 3eabc7e8b922
Revises: 31572b9c8148
Create Date: 2025-12-12 09:40:37.074278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eabc7e8b922'
down_revision = '31572b9c8148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_status'))
        batch_op.drop_column('size')
        batch_op.drop_column('image')
        batch_op.drop_column('condition')
        batch_op.drop_column('status')
        batch_op.drop_column('price')
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_status'), ['status'], unique=False)

    op.drop_table('inventory_variations')
    # ### end Alembic commands ###
