"""empty message

Revision ID: 6c7ad2eeb116
Revises: be6a80483982
Create Date: 2025-12-20 12:34:11.257539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7ad2eeb116'
down_revision = 'be6a80483982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
