"""edit order table

Revision ID: 771bae4e0637
Revises: e2164486c515
Create Date: 2025-12-14 16:55:14.146792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771bae4e0637'
down_revision = 'e2164486c515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_variation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_ss', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory_variations', ['inventory_variation_id'], ['id'])
        batch_op.drop_column('item_name')
        batch_op.drop_column('size')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_ss')
        batch_op.drop_column('inventory_variation_id')

    # ### end Alembic commands ###
