"""empty message

Revision ID: 78e37085e933
Revises: 7cc667397b4d
Create Date: 2025-12-21 19:46:34.231757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e37085e933'
down_revision = '7cc667397b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
