"""empty message

Revision ID: 7dcb645d5492
Revises: 27ed2fbcf71c
Create Date: 2025-12-20 11:55:07.936306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcb645d5492'
down_revision = '27ed2fbcf71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
