"""empty message

Revision ID: 83e4ac36969f
Revises: 3eabc7e8b922
Create Date: 2025-12-12 17:12:54.078512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e4ac36969f'
down_revision = '3eabc7e8b922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
