"""empty message

Revision ID: 8ce88fb19cd7
Revises: 3919a0506632
Create Date: 2025-12-18 22:29:00.817827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce88fb19cd7'
down_revision = '3919a0506632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
