"""add spent to inventory var

Revision ID: 932e518edcbe
Revises: 4be4fc8a70b2
Create Date: 2026-01-11 10:20:25.111673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932e518edcbe'
down_revision = '4be4fc8a70b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_variations', schema=None) as batch_op:
        batch_op.drop_column('spent')

    # ### end Alembic commands ###
