"""Add customer address

Revision ID: 979bd596e32e
Revises: 98ba28a5bdb2
Create Date: 2025-12-06 15:24:51.799858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979bd596e32e'
down_revision = '98ba28a5bdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
