"""remove inventory_id & variation_id in orders table

Revision ID: a088296b5ad7
Revises: e57b13e53de2
Create Date: 2026-02-15 08:29:44.046027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a088296b5ad7'
down_revision = 'e57b13e53de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocr_jobs', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('orders_inventory_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_variation_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'inventory_id')
    op.drop_column('orders', 'variation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('variation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_variation_id_fkey'), 'orders', 'inventory_variations', ['variation_id'], ['id'])
    op.create_foreign_key(op.f('orders_inventory_id_fkey'), 'orders', 'inventory', ['inventory_id'], ['id'])
    op.alter_column('ocr_jobs', 'image_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
