"""empty message

Revision ID: b49afcbf3fce
Revises: 00903b388a68
Create Date: 2025-12-07 16:49:40.424900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49afcbf3fce'
down_revision = '00903b388a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_customers_psid'))
        batch_op.create_index(batch_op.f('ix_customers_sender_id'), ['sender_id'], unique=True)
        batch_op.drop_column('psid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_customers_sender_id'))
        batch_op.create_index(batch_op.f('ix_customers_psid'), ['psid'], unique=True)
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
