"""empty message

Revision ID: b6a7f94f05e2
Revises: 6c7ad2eeb116
Create Date: 2025-12-20 12:35:05.891989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a7f94f05e2'
down_revision = '6c7ad2eeb116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
