"""empty message

Revision ID: be6a80483982
Revises: 35bffb29002c
Create Date: 2025-12-20 12:30:14.673044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6a80483982'
down_revision = '35bffb29002c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
