"""remove uniq sender_id in leads

Revision ID: e2164486c515
Revises: 2a4c02c37e0c
Create Date: 2025-12-13 19:03:44.564627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2164486c515'
down_revision = '2a4c02c37e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_leads_sender_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_sender_id'), ['sender_id'], unique=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
