"""web & messenger workflow

Revision ID: e57b13e53de2
Revises: d6322c2dfbc2
Create Date: 2026-01-31 19:51:35.752777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57b13e53de2'
down_revision = 'd6322c2dfbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'proof_submitted', 'approved', 'rejected', 'expired', name='checkout_status'), nullable=False),
    sa.Column('proof_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkout_sessions_customer_id'), ['customer_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['inventory_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guest_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_guest_id'), ['guest_id'], unique=True)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_session_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_unique_constraint(None, ['checkout_session_id'])
        batch_op.create_foreign_key(None, 'checkout_sessions', ['checkout_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('total_price')
        batch_op.drop_column('checkout_session_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_customers_guest_id'))
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('guest_id')
        batch_op.drop_column('user_id')

    op.drop_table('order_items')
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_customer_id'))

    op.drop_table('checkout_sessions')
    # ### end Alembic commands ###
