"""remove customer address

Revision ID: ef0fba976416
Revises: 979bd596e32e
Create Date: 2025-12-06 15:27:02.499710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0fba976416'
down_revision = '979bd596e32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
