"""empty message

Revision ID: f83161008aec
Revises: 8ce88fb19cd7
Create Date: 2025-12-18 22:36:51.038047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83161008aec'
down_revision = '8ce88fb19cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
